-- Repair counters.library_assets (migration 0021) from the source of truth.
--
-- The counter is trigger-maintained and every real writer keeps it exact, so
-- this should never be needed. Run it if the count is suspect — the known way
-- to drift it is `INSERT OR REPLACE INTO assets`, which fires the INSERT
-- trigger but not the DELETE trigger (SQLite only fires the latter for REPLACE
-- when PRAGMA recursive_triggers is on, and it is off by default). No writer
-- does that today; d1-real-schema.test.ts pins both the drift and this repair.
--
--   npx wrangler d1 execute wagmiphotos --remote --file=scripts/recount-library.sql
--
-- Costs one full scan of assets (~511k rows) — that is the read this migration
-- exists to remove from the request path, so keep it an operator action and
-- never wire it into a handler or the cron.
--
-- BULK IMPORTS. SQLite triggers are per-ROW, not per-statement: a 200-row bulk
-- INSERT fires the counter trigger 200 times, so a large import writes one
-- extra D1 row per asset. Measured on 200k rows (batches of 200), against a
-- 407ms baseline with neither present:
--
--   triggers only          439ms   +8%    +0.16 us/row
--   showcase index only    502ms  +23%    +0.48 us/row
--   both (as shipped)      539ms  +32%    +0.66 us/row
--
-- Note the index costs 3x what the triggers do: if you only drop one thing for
-- a big load, drop idx_assets_showcase (at the cost of a slow /v1/home until
-- it is recreated), not the triggers. Dropping the triggers additionally means
-- the counter is wrong until the recount below runs.
--
-- For a very large import (millions of rows), drop both, load, then recount:
--
--   DROP TRIGGER IF EXISTS counters_assets_after_insert;
--   DROP TRIGGER IF EXISTS counters_assets_after_update;
--   DROP TRIGGER IF EXISTS counters_assets_after_delete;
--   DROP INDEX   IF EXISTS idx_assets_showcase;
--   -- ... run the import ...
--   -- then re-apply 0021 directly (`migrations apply` will not re-run an
--   -- already-recorded migration):
--   npx wrangler d1 execute wagmiphotos --remote \
--     --file=migrations/0021_home_read_cost.sql
--
-- Every statement in 0021 is CREATE ... IF NOT EXISTS plus an ON CONFLICT
-- upsert that recounts, so re-running it restores the index, the triggers AND
-- the correct count in one step — this script is not needed in that flow. It
-- exists to repair drift when the schema is already in place.
UPDATE counters
   SET value = (SELECT COUNT(*) FROM assets WHERE collection_id IS NULL AND dead_at IS NULL)
 WHERE name = 'library_assets';
